version: '3.8'

services:
  nmapscanner:
    build:
      context: ./Nmap
      dockerfile: Dockerfile
    container_name: nmapscanner
    volumes:
      - ./results:/app/results
    working_dir: /app
    entrypoint: ["python3", "nmapscan.py"]
    networks:
      - secnet

  tshark:
    build:
      context: ./Tshark
      dockerfile: Dockerfile
    container_name: tshark
    volumes:
      - ./results:/app/results
    working_dir: /app
    entrypoint: ["python3", "capture_tshark.py"]
    cap_add:
      - NET_RAW
      - NET_ADMIN
    network_mode: "host"

networks:
  secnet:
    driver: bridge
